Add a setops deployment workflow
setopsco/github-actions pull request #1
Opened 2022-03-14 06:30 UTC by hzeus

2022-03-14 18:30 UTC, kevinscholz requested changes
Great work, this already looks really good 👏 Thanks for investing the time to provide the workflow and the actions.

I added a few questions/comments. After we addressed them I'd do a final round of testing and then we should be good to go.

2022-03-14 18:30 UTC, kevinscholz commented on build-and-push-image/action.yml
> +description: "Builds the docker images and pushes it to the SetOps registry while creating a tag for each stage / app combination"
```suggestion
description: "Builds the Docker images and pushes it to the SetOps registry while creating a tag for each stage / app combination"
```

2022-03-14 18:30 UTC, kevinscholz commented on build-and-push-image/action.yml
> +    description: The SetOps username, usually obtained via secrets.SETOPS_USER
`secrets.SETOPS_USER` isn't known on this level, so I'd remove it from the description.

2022-03-14 18:30 UTC, kevinscholz commented on build-and-push-image/action.yml
> +    description: The SetOps password, usually obtained via secrets.SETOPS_PASSWORD
secrets.SETOPS_PASSWORD isn't known on this level, so I'd remove it from the description.

2022-03-14 18:30 UTC, kevinscholz commented on build-and-push-image/action.yml
> +    - name: "Install Setops"
```suggestion
    - name: "Install SetOps"
```

2022-03-14 18:30 UTC, kevinscholz commented on deployment/action.yml
> +        echo "Changeset for creating releases"
I think this step could be split up in multiple steps for simplicity. Do you agree?

2022-03-14 18:30 UTC, kevinscholz commented on deployment/action.yml
> +        predeploy_command="${{ inputs.predeploy-command }}"
Could this include double quotes? If so, should they be escaped via Github Action syntax?

2022-03-14 18:34 UTC, kevinscholz commented on deployment/action.yml
> +          apps_with_release_id[$app]=$(sos --app $app release:create ${{ inputs.image-digest }} | grep -o 'ReleaseID.*' | grep -o '[0-9].*')
Linter:
```suggestion
          apps_with_release_id[$app]=$(sos --app "$app" release:create ${{ inputs.image-digest }} | grep -o 'ReleaseID.*' | grep -o '[0-9].*')
```

2022-03-14 18:35 UTC, kevinscholz commented on deployment/action.yml
> +          sos --app $app release:activate $release_id
Linter:
```suggestion
          sos --app "$app" release:activate "$release_id"
```

2022-03-14 18:35 UTC, kevinscholz commented on deployment/action.yml
> +          sos --app $first_app task:run --debug --release $release_id_of_first_app -- bash -c "${{ inputs.predeploy-command }} && echo 'SETOPS_SUCCESS'" | tee /dev/stderr | grep "SETOPS_SUCCESS" > /d
Linter
```suggestion
          sos --app "$first_app" task:run --debug --release "$release_id_of_first_app "-- bash -c "${{ inputs.predeploy-command }} && echo 'SETOPS_SUCCESS'" | tee /dev/stderr | grep "SETOPS_SUCCESS" > /dev/null
```

2022-03-18 13:32 UTC, kevinscholz commented on deployment/action.yml
> +        echo "Changeset for creating releases"
Decided to not do it now

2022-03-18 14:31 UTC, hzeus commented
@kevinscholz Thanks for the updates, looks very good to me 👍

2022-03-18 14:33 UTC, merged